// Generated by dts-bundle-generator v5.9.0

export interface KeypairBytes {
	pubkey: Uint8Array;
	secret: Uint8Array;
}
/**
 * These are the basic crypto primitives we need.
 * There are several implementations which provide this interface,
 * e.g. native Node, Chloride, etc.
 * These all handle Uint8Arrays (bytes)
 */
export interface ICryptoDriver {
	sha256(input: string | Uint8Array): Uint8Array;
	generateKeypairBytes(): KeypairBytes;
	sign(keypairBytes: KeypairBytes, msg: string | Uint8Array): Uint8Array;
	verify(publicKey: Uint8Array, sig: Uint8Array, msg: string | Uint8Array): boolean;
}
/**
 * A verison of the ILowLevelCrypto interface backed by native Node crypto functions.
 * Requires a recent version of Node, perhaps 12+?
 * Does not work in the browser.
 */
export declare const CryptoDriverNode: ICryptoDriver;

export {};
